include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - annotate_overrides
    - directives_ordering
    - omit_local_variable_types
    - prefer_const_constructors
    - unnecessary_const
    - unnecessary_overrides
